---
name: "Mastodon: upload-static"
on:
  workflow_dispatch:

env:
  IMAGE: "ghcr.io/bencord0/mastodon:master"

permissions:
  id-token: write

jobs:
  upload-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure AWS Credentials
      run: |
        ./scripts/setup_aws_credentials.py \
          --role "arn:aws:iam::055237546114:role/mastodon-upload-assets"

    - name: Upload Static Assets
      run: |
        aws sts get-caller-identity
        docker run --rm \
          --env ${{ env.AWS_ROLE_ARN }} \
          --env ${{ env.AWS_WEB_IDENTITY_TOKEN_FILE }} \
          --volume $(dirname ${{ env.AWS_WEB_IDENTITY_TOKEN_FILE }}) \
          ${{ env.IMAGE }} \
          aws sts get-caller-identity
          #cat ${{ env.AWS_WEB_IDENTITY_TOKEN_FILE }}
          #aws s3 cp --debug --recursive /usr/share/mastodon/public/ s3://nfra-club/

