name: 'Terraform'

on:
  push:
    branches:
    - production
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  eu-west-2:
    uses: condime/terraform-plans/.github/workflows/terraform-run.yml@production
    with:
      region: eu-west-2
    secrets:
      CONSUL_HTTP_TOKEN: ${{ secrets.CONSUL_HTTP_TOKEN }}
      ARTIFACT_SECRET_KEY: ${{ secrets.ARTIFACT_SECRET_KEY }}

  us-east-1:
    uses: condime/terraform-plans/.github/workflows/terraform-run.yml@production
    with:
      region: us-east-1
    secrets:
      CONSUL_HTTP_TOKEN: ${{ secrets.CONSUL_HTTP_TOKEN }}
      ARTIFACT_SECRET_KEY: ${{ secrets.ARTIFACT_SECRET_KEY }}
