name: 'Terraform Import'

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region Name'
        required: true
      resource:
        description: 'Resource Address'
        required: true
      id:
        description: 'Resource ID'
        required: true

env:
  # Repository specific, contact @bencord0 to rotate
  CONSUL_HTTP_TOKEN: ${{ secrets.CONSUL_HTTP_TOKEN }}
  AWS_DEFAULT_REGION: ${{ github.event.inputs.region }}

permissions:
  id-token: write

jobs:
  terraform-import:
    name: 'Terraform Import'
    environment: production
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      run: |
        ./scripts/setup_aws_credentials.py \
          --role "arn:aws:iam::055237546114:role/terraform-plans"

    - name: Terraform Import
      run: ./scripts/terraform_import.sh "${{ github.event.inputs.resource }}" "${{ github.event.inputs.id }}"
