name: 'Terraform Taint'

on:
  workflow_dispatch:
    inputs:
      resource:
        description: 'Resource Address'
        required: true

env:
  # Repository specific, contact @bencord0 to rotate
  CONSUL_HTTP_TOKEN: ${{ secrets.CONSUL_HTTP_TOKEN }}

jobs:
  terraform-import:
    name: 'Terraform Import'
    environment: production
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Taint a terraform resource
    - name: Terraform Taint
      run: |
        terraform taint "${{ github.event.inputs.resource }}"
