name: 'Terraform Refresh'

on:
  workflow_dispatch:

env:
  # Repository specific, contact @bencord0 to rotate
  CONSUL_HTTP_TOKEN: ${{ secrets.CONSUL_HTTP_TOKEN }}

permissions:
  id-token: write

jobs:
  terraform-refresh:
    name: 'Terraform Refresh'
    environment: production
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: ["eu-west-1", "eu-west-2", "us-east-1"]

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      run: |
        ./scripts/setup_aws_credentials.py \
          --role "arn:aws:iam::055237545114:role/terraform-plans-ro"

    # Refresh terraform state
    - name: Terraform Refresh
      run: ./scripts/terraform_refresh.sh
      env:
        AWS_DEFAULT_REGION: ${{ matrix.region }}
